# Generated by Django 6.0.4 on 2026-05-26 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_alter_task_options_alter_task_is_completed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название курса')),
                ('duration_months', models.IntegerField(verbose_name='Длительность (в месяцах)')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя студента')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('courses', models.ManyToManyField(related_name='students', to='bboard.course', verbose_name='Курсы')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
