# Generated by Django 6.0.4 on 2026-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_hwarticle_remove_student_courses_delete_course_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Владелец счета')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, max_length=10, verbose_name='Баланс')),
            ],
        ),
    ]
