# Generated by Django 6.0.4 on 2026-05-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_bankaccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HwArticle',
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Баланс'),
        ),
    ]
