# Generated by Django 6.0.4 on 2026-05-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_delete_hwarticle_alter_bankaccount_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('specifications', models.JSONField(blank=True, default=dict, verbose_name='Технические характеристики (JSON)')),
            ],
        ),
        migrations.DeleteModel(
            name='BankAccount',
        ),
    ]
