# Generated by Django 6.0.4 on 2026-07-23 15:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название абонемента')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (тенге)')),
                ('duration_days', models.PositiveIntegerField(verbose_name='Срок действия (дней)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='subscriptions/', verbose_name='Картинка')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя тренера')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специализация')),
                ('bio', models.TextField(verbose_name='О тренере')),
                ('experience_years', models.PositiveIntegerField(verbose_name='Опыт (лет)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainers/', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата тренировки')),
                ('time', models.TimeField(verbose_name='Время тренировки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.trainer', verbose_name='Тренер')),
            ],
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateField(auto_now_add=True, verbose_name='Дата покупки')),
                ('end_date', models.DateField(verbose_name='Дата окончания')),
                ('subscription_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fitness.subscriptiontype', verbose_name='Абонемент')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
