# Generated by Django 6.0.4 on 2026-07-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='telegram_chat_id',
            field=models.CharField(default=0, help_text='Ваш ID из Telegram', max_length=50, verbose_name='Telegram Chat ID'),
            preserve_default=False,
        ),
    ]
