# Generated by Django 6.0.4 on 2026-07-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_alert_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='telegram_chat_id',
            field=models.CharField(default='0', max_length=50, verbose_name='Telegram Chat ID'),
        ),
    ]
