# Generated by Django 6.0.4 on 2026-07-14 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название монеты')),
                ('symbol', models.CharField(max_length=10, verbose_name='Тикер (например, BTC)')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=18, verbose_name='Количество')),
                ('buy_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Цена покупки (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Крипто-актив',
                'verbose_name_plural': 'Крипто-активы',
            },
        ),
    ]
