# Generated by Django 6.0.4 on 2026-07-14 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptoasset',
            options={},
        ),
        migrations.RemoveField(
            model_name='cryptoasset',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='buy_price',
            field=models.DecimalField(decimal_places=2, max_digits=18, verbose_name='Цена покупки'),
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='symbol',
            field=models.CharField(max_length=10, verbose_name='Тикер'),
        ),
        migrations.AlterField(
            model_name='cryptoasset',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
