# Generated by Django 6.0.4 on 2026-07-21 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Марка и модель авто')),
                ('car_type', models.CharField(choices=[('sedan', 'Седан'), ('suv', 'Внедорожник'), ('sport', 'Спортивный'), ('electric', 'Электромобиль')], default='sedan', max_length=20, verbose_name='Тип кузова')),
                ('capacity', models.IntegerField(default=5, verbose_name='Количество мест')),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за час ($)')),
                ('description', models.TextField(blank=True, verbose_name='Описание авто')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cars/', verbose_name='Фото машины')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата аренды')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(verbose_name='Время окончания')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Клиент')),
                ('booking_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework29.bookingobject', verbose_name='Автомобиль')),
            ],
        ),
    ]
