# Generated by Django 6.0.4 on 2026-07-21 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework29', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingobject',
            name='image',
        ),
        migrations.AddField(
            model_name='bookingobject',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на фото'),
        ),
        migrations.AddField(
            model_name='bookingobject',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Цена за день (₽)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookingobject',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена за час (₽)'),
        ),
    ]
