# Generated by Django 6.0.4 on 2026-06-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework29', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название документа')),
                ('file', models.FileField(upload_to='documents/', verbose_name='Файл (xlsx / pdf)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
            ],
        ),
        migrations.DeleteModel(
            name='Homework32Result',
        ),
        migrations.DeleteModel(
            name='SeparatePost',
        ),
    ]
