# Generated by Django 6.0.4 on 2026-06-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework29', '0006_alter_projectnote_options_alter_projectnote_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
            ],
        ),
        migrations.DeleteModel(
            name='ProjectNote',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
