# Generated by Django 6.0.4 on 2026-06-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework29', '0010_task_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
        migrations.AlterField(
            model_name='task',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
